src/Entity/Ticket.php
<?php

namespace App\Entity;

use App\Repository\TicketRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=TicketRepository::class)
 */
class Ticket
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $files;

    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="create")
     */
    private $created_date;

    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="update")
     */
    private $updated_date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $priority;

    /**
     * @ORM\ManyToOne(targetEntity=TicketType::class, inversedBy="tickets")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ticket_type;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="tickets")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;


    /**
     * @ORM\ManyToOne(targetEntity=Status::class, inversedBy="tickets")
     * @ORM\JoinColumn(nullable=false)
     */
    private $status;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $state;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="tickets")
     */
    private $responsible;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="tickets")
     */
    private $author;





    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getFiles()
    {
        return $this->files;
    }

    public function setFiles($files)
    {
        $this->files = $files;

        return $this;
    }

    public function getCreatedDate(): ?\DateTimeInterface
    {
        return $this->created_date;
    }



    public function getUpdatedDate(): ?\DateTimeInterface
    {
        return $this->updated_date;
    }



    public function getPriority(): ?string
    {
        return $this->priority;
    }

    public function setPriority(string $priority): self
    {
        $this->priority = $priority;

        return $this;
    }

    public function getTicketType(): ?TicketType
    {
        return $this->ticket_type;
    }

    public function setTicketType(?TicketType $ticket_type): self
    {
        $this->ticket_type = $ticket_type;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getStatus(): ?Status
    {
        return $this->status;
    }

    public function setStatus(?Status $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getState(): ?bool
    {
        return $this->state;
    }

    public function setState(?bool $state): self
    {
        $this->state = $state;

        return $this;
    }
    public function __toString()
    {
        return (string) $this;
    }

    public function getResponsible(): ?User
    {
        return $this->responsible;
    }

    public function setResponsible(?User $responsible): self
    {
        $this->responsible = $responsible;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }
}

src/Controller/SupportController.php
<?php

namespace App\Controller;

use App\Entity\Status;
use App\Entity\Ticket;
use App\Form\AssignType;
use App\Form\ProgressType;
use Doctrine\ORM\Mapping\Id;
use App\Form\ValidTicketType;
use App\Repository\TicketRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;


/**
 * @Route("support_space")
 */
class SupportController extends AbstractController
{
    private $em;

    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }
    /**
     * @Route("/support", name="support")
     */
    public function index(TicketRepository $ticketRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_SUPPORT');

        return $this->render('support/supportTable.html.twig', [
            'tickets' => $ticketRepository->findBy(array('responsible' => null), array('priority' => 'DESC')),
        ]);
    }
    /**
     * @Route("/support-tab", name="support_tab")
     */
    public function supportTab(TicketRepository $ticketRepository, UserInterface $responsible): Response
    {
        $this->denyAccessUnlessGranted('ROLE_SUPPORT');

        return $this->render('support/supportTable.html.twig', [
            'tickets' => $ticketRepository->findTicketByResponsible($responsible),
        ]);
    }
    /**
     * @Route("/support-progress/{ticket}", name="support_progress", methods={"GET","POST"}, requirements={"ticket"="\d+"})
     */
    public function progress(Request $request, Ticket $ticket): Response
    {
        $this->denyAccessUnlessGranted('ROLE_SUPPORT');

        $form = $this->createForm(ProgressType::class, $ticket);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->em->flush();

            return $this->redirectToRoute('support_tab');
        }

        return $this->render('support/progress.html.twig', [
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("support-assign/{id}", name="support_assign", methods={"GET","POST"})
     */
    public function  assign(Request $request, Ticket $ticket): Response
    {
        $this->denyAccessUnlessGranted('ROLE_SUPPORT');

        $form = $this->createForm(AssignType::class, $ticket);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->em->flush();

            return $this->redirectToRoute('support_tab');
        }

        return $this->render('support/assign.html.twig', [
            'ticket' => $ticket,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("valid/{id}", name="valid_ticket")
     */
    public function  valid(Request $request, Ticket $ticket): Response
    {
        $this->denyAccessUnlessGranted('ROLE_SUPPORT');

        $form = $this->createForm(ValidTicketType::class, $ticket);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->em->flush();

            return $this->redirectToRoute('support');
        }

        return $this->render('support/valid.html.twig', [
            'ticket' => $ticket,
            'form' => $form->createView(),
        ]);
    }
}

templates/support/assign.html.twig
{% extends 'support.html.twig' %}

{% block body %}
	{{ form_start(form) }}
	<div class="container mt-5">
		<div class="col-6 mx-auto">
			{{ form_widget(form) }}
			<button class="btn btn-success">{{ button_label|default('Assign') }}</button>
		</div>
	</div>
	{{ form_end(form) }}


{% endblock %}

templates/support/progress.html.twig
{% extends 'support.html.twig' %}

{% block body %}
	{{ form_start(form) }}
	<div class="container mt-5">
		<div class="col-6 mx-auto">
			{{ form_widget(form) }}
			<button class="btn btn-success">{{ button_label|default('Mark') }}</button>
		</div>
	</div>
	{{ form_end(form) }}


{% endblock %}

templates/support/support.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello Supporter!
{% endblock %}

{% block body %}
	<body class=" text-white bg-dark">
		<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
			<header class="mb-auto">
				<div>
					{% if is_granted('IS_AUTHENTICATED_FULLY') %}
						<body>
							<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
								<a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Support Space</a>
								<input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
								<ul class="navbar-nav px-3">
									<li class="nav-item text-nowrap">
										<a class="btn btn-outline-danger" href="{{ path('app_logout')}}">Sign out</a>
									</li>
								</ul>
							</nav>

							<div class="container-fluid">
								<div class="row">
									<nav class="col-md-2 d-none d-md-block bg-dark sidebar">
										<div class="sidebar-sticky">
											<ul class="nav flex-column">
												<li class="nav-item">
													<a class="nav-link active" aria-current="page" href="#">
														<span data-feather="home"></span>
														Dashboard
													</a>
												</li>
												<li class="nav-item">
													<a class="nav-link text-white" href="{{path('support_tab')}}">
														<span data-feather="file"></span>
														Tickets
													</a>
												</li>
												<li class="nav-item">
													<a class="nav-link text-white" href="{{path('messages')}}">
														<span data-feather="shopping-cart"></span>
														Messages
													</a>
												</li>
												<li class="nav-item">
													<a class="nav-link text-white" href="#">
														<span data-feather="users"></span>
														Recently updated
													</a>
												</li>
												<li class="nav-item">
													<a class="nav-link text-white" href="#">
														<span data-feather="bar-chart-2"></span>
														Solved
													</a>
												</li>
												<li class="nav-item">
													<a class="nav-link text-white" href="#">
														<span data-feather="layers"></span>
														closed
													</a>
												</li>
											</ul>

											<h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
												<span>Saved reports</span>
												<a class="d-flex align-items-center text-muted" href="#">
													<span data-feather="plus-circle"></span>
												</a>
											</h6>
											<ul class="nav flex-column mb-2">
												<li class="nav-item">
													<a class="nav-link" href="#">
														<span data-feather="file-text"></span>
														Current month
													</a>
												</li>
												<li class="nav-item">
													<a class="nav-link" href="#">
														<span data-feather="file-text"></span>
														Last quarter
													</a>
												</li>
												<li class="nav-item">
													<a class="nav-link" href="#">
														<span data-feather="file-text"></span>
														Social engagement
													</a>
												</li>
												<li class="nav-item">
													<a class="nav-link" href="#">
														<span data-feather="file-text"></span>
														Year-end sale
													</a>
												</li>
											</ul>
										</div>
									</nav>
									<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
										<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
											<h1 class="h2">Dashboard</h1>
											<div class="btn-toolbar mb-2 mb-md-0">
												<div class="btn-group mr-2">
													<button class="btn btn-sm btn-outline-secondary">Share</button>
													<button class="btn btn-sm btn-outline-secondary">Export</button>
												</div>
												<button class="btn btn-sm btn-outline-secondary dropdown-toggle">
													<span data-feather="calendar"></span>
													This week
												</button>
											</div>
										</div>
									{% endif %}
									<nav class="nav nav-masthead justify-content-center float-md-end">
										<div class="text-end">
											{% if is_granted('IS_AUTHENTICATED_FULLY') %}
												{% else %}
													<a class="btn btn-outline-primary me-2" href="{{ path('app_login')}}">Sign-in</a>
													<a class="btn btn-warning" href="{{ path('app_register')}}">Sign-up</a>
											{% endif %}

										</div>
									</nav>
								</div>
							</body>
						</body>
					</body>
				</header>
			</div>
		</body>
	</body>
{% endblock %}

templates/support/supportTable.html.twig
{% extends 'support.html.twig' %}

{% block title %}{% endblock %}

{% block content %}
	{% for message in app.flashes('notice') %}
		<div class="flash-notice">
			{{ message }}
		</div>
	{% endfor %}
	<div class="table-responsive">
		<div class="row my-5">
			<div class="">
				<div class="card">
					<table class="table table-striped table-sm">
						<thead>
							<tr>
								<th scope="col">Id</th>
								<th scope="col">Status</th>
								<th scope="col">Type</th>
								<th scope="col">Category</th>
								<th scope="col">Title</th>
								<th scope="col">Responsible</th>
								<th scope="col">Description</th>
								<th scope="col">Files</th>
								<th scope="col">Created_date</th>
								<th scope="col">updated_date</th>
								<th scope="col">Priority</th>
								<th scope="col">State</th>
								<th scope="col">Actions</th>
							</tr>
						</thead>
						<tbody>
							{% for ticket in tickets %}

								<tr>
									{% set colorState = ticket.state == 0 ? 'danger' : 'success' %}
									{% set colorStatus = ticket.status == "New" ? 'success' : 'danger' %}
									{% set colorPriority = ticket.priority  ==  "very urgent" ? 'danger' : ticket.priority  ==  "urgent" ? 'warning' :   
                                                                                ticket.priority  ==  "primary" ? '#ff6600' :  "success" 
                                    %}
									<td scope="row">{{ ticket.id }}</td>
									<td>
										<span class="badge bg-{{colorStatus}}">{{ ticket.status }}</span>
									</td>
									<td>{{ticket.ticketType.name}}</td>
									<td>{{ticket.category.name}}</td>
									<td>{{ ticket.titre }}</td>
									{% if ticket.responsible is null %}
										<td>
											<span class="badge bg-warning">Not assigned</span>
										</td>
									{% else %}
										<td>{{ ticket.responsible }}</td>
									{% endif %}
									<td>{{ ticket.description }}</td>
									<td>{{ ticket.files }}</td>
									<td>{{ ticket.createddate|date }}</td>
									<td>{{ ticket.updateddate|date }}</td>
									<td>
										<span class="badge bg-{{colorPriority}}">{{ ticket.priority }}</span>
									</td>
									<td>
										<span class="badge bg-{{colorState}}">{{ ticket.state ? 'Valid' : 'Follow' }}</span>
									</td>
									<td>
										{% if ticket.responsible is null %}
											<a href="{{ path('support_assign', {'id': ticket.id}) }}" class="btn btn-sm btn-primary text-light">Assign</a>

											<a href="{{ path('valid_ticket', {'id': ticket.id}) }}" class="btn btn-sm btn-success text-light">Validate</a>
										{% else %}
											<button type="button" class="btn-sm" disabled>Assigned</button>
											<a href="{{ path('support_progress', {'ticket': ticket.id}) }}" class="btn btn-sm btn-info text-light">Mark</a>

										{% endif %}
									</td>
								</tr>
							</td>
						</tbody>
					</tr>

				{% else %}
					<tr>
						<td colspan="7">No ticket
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>


	</div>
</div></div></div>{% endblock %}

templates/support/valid.html.twig
{% extends 'support.html.twig' %}

{% block body %}

{{ form_start(form) }}
<div class="container mt-5">
	<div class="col-6 mx-auto">
		{{ form_widget(form) }}
		<button class="btn btn-success">{{ button_label|default('save') }}</button>
	</div{{form_end(form)}} {% endblock %}