src/Entity/Messages.php
<?php

namespace App\Entity;

use App\Repository\MessagesRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;


/**
 * @ORM\Entity(repositoryClass=MessagesRepository::class)
 */
class Messages
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $message;

    /**
     * @ORM\Column(type="datetime_immutable")
     * @Gedmo\Timestampable(on="create")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_read = 0;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="sent")
     * @ORM\JoinColumn(nullable=false)
     */
    private $sender;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="received")
     * @ORM\JoinColumn(nullable=false)
     */
    private $recipient;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getIsRead(): ?bool
    {
        return $this->is_read;
    }

    public function setIsRead(bool $is_read): self
    {
        $this->is_read = $is_read;

        return $this;
    }

    public function getSender(): ?User
    {
        return $this->sender;
    }

    public function setSender(?User $sender): self
    {
        $this->sender = $sender;

        return $this;
    }

    public function getRecipient(): ?User
    {
        return $this->recipient;
    }

    public function setRecipient(?User $recipient): self
    {
        $this->recipient = $recipient;

        return $this;
    }
}

src/Form/MessageType.php
<?php

namespace App\Form;

use App\Entity\User;
use App\Entity\Messages;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class MessageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                "attr" => [
                    "class" => "form-control"
                ]
            ])
            ->add('message', TextareaType::class, [
                "attr" => [
                    "class" => "form-control"
                ]
            ])
            ->add('recipient', EntityType::class, [
                "class" => User::class,
                "choice_label" => "email",
                "attr" => [
                    "class" => "form-control"
                ]
            ])
            ->add('envoyer', SubmitType::class, [
                "attr" => [
                    "class" => "btn btn-primary"
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Messages::class,
        ]);
    }
}

src/Controller/MessagesController.php
<?php

namespace App\Controller;

use App\Entity\Messages;
use App\Form\MessageType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MessagesController extends AbstractController
{
    private $em;

    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }
    /**
     * @Route("/messages", name="messages")
     */
    public function index(): Response
    {
        return $this->render('messages/index.html.twig', [
            'controller_name' => 'MessagesController',
        ]);
    }
    /**
     * @Route("/send", name="send")
     */
    public function send(Request $request): Response
    {
        $message = new Messages;
        $form = $this->createForm(MessageType::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $message->setSender($this->getUser());

            $this->em->persist($message);
            $this->em->flush();

            $this->addFlash("message", "message sent successfully.");
            return $this->redirectToRoute("messages");
        }

        return $this->render("messages/send.html.twig", [
            "form" => $form->createView()
        ]);
    }
    /**
     * @Route("/received", name="received")
     */
    public function received(): Response
    {
        return $this->render('messages/received.html.twig');
    }
    /**
     * @Route("/read/{id}", name="read")
     */
    public function read(Messages $message): Response
    {
        $message->setIsRead(true);

        $this->em->persist($message);
        $this->em->flush();

        return $this->render('messages/read.html.twig', compact("message"));
    }
    /**
     * @Route("/delete/{id}", name="deletemessage")
     */
    public function delete(Messages $message): Response
    {

        $this->em->remove($message);
        $this->em->flush();

        return $this->redirectToRoute("received");
    }
}

templates/messages/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messenger
{% endblock %}

{% block body %}
	<section class="container">
		<div class="col-6 mx-auto">
			<div class="row">
				<div class="col">
					<h1>Messenger</h1>
					<p>Received :{{ app.user.received|length }}</p>
					<p>Sent :{{ app.user.sent|length }}</p>
					<a href="{{path("send")}}" class="btn btn-primary">Send a Message</a>
					<a href="{{path("received")}}" class="btn btn-info">Mailbox</a>
				</div>
			</div>
		</section>
	{% endblock %}

templates/messages/read.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messenger
{% endblock %}

{% block body %}
	<section class="container">
		<div class="col-6 mx-auto">
			<div class="row">
				<div class="col">
					<h1>Messenger</h1>
					<h2>{{ message.title }}</h2>
					<p>Message from
						{{ message.sender.email }}</p>
					<p>at
						{{ message.createdAt|date }}</p>
					<div>{{ message.message }}</div>
					<a href="{{path("received")}}" class="btn btn-primary">return to Mailbox</a>

				</div>
			</div>
		</section>
	{% endblock %}

templates/messages/received.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messenger
{% endblock %}

{% block body %}
	<section class="container">
		<div class="col-6 mx-auto">
			<div class="row">
				<div class="col-12">
					<h1>Messenger</h1>
					<h2>Mailbox</h2>
					<p>You received
						{{ app.user.received|length }}
						messages</p>
				</div>
				<div class="col-3">from</div>
				<div class="col-3">Subject</div>
				<div class="col-3">Date</div>
				<div class="col-3">Actions</div>
				{% for message in app.user.received %}
					{% set bold = "" %}
					{% if message.isRead == 0 %}
						{% set bold = "fw-bold" %}
					{% endif %}
					<div class="col-3 {{bold}}">{{ message.sender.email }}</div>
					<div class="col-3 {{bold}}">
						<a href="{{ path("read", {id: message.id}) }}">{{ message.title }}</a>
					</div>
					<div class="col-3 {{bold}}">{{ message.createdAt|date }}</div>
					<div class="col-3">
						<a href="{{ path("deletemessage", {id: message.id}) }}">
							<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewbox="0 0 16 16">
								<path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
								<path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
							</svg>
						</a>
					</div>

				{% endfor %}
			</div>
			<a href="{{path("send")}}" class="btn btn-primary">Send a Message</a>
		</div>
	</section>
{% endblock %}

templates/messages/send.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messenger
{% endblock %}

{% block body %}
	<section class="container">
		<div class="col-6 mx-auto">
			<div class="row">
				<div class="col">
					<h1>Send a message</h1>
					{{ form(form) }}
					</div>
				</div>
			</section>
		{% endblock %}